# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cdb8fe89798f0f047394c93220dd24e89a506105185766f89a729c2746ac1cf2fe33bdb8c7a2e1b4d257f1ad031e71731e7285b491b66b4fc239295ff4fe94c6

test:
  secret_key_base: ccc162257b69b798827b3605bd5e8541e0de05117a223cf187ab18997719c023dffe4520717b74459464e38bcf82354609e0ee76438517d9bc692c741e2599af

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
